version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: pwp-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - pwp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pwp-backend
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/pwp?authSource=admin
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=24h
      - OPENROUTESERVICE_API_KEY=${OPENROUTESERVICE_API_KEY}
      - ALLOWED_ORIGINS=http://localhost:8080
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - pwp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pwp-frontend
    restart: always
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - pwp-network

networks:
  pwp-network:
    driver: bridge

volumes:
  mongodb_data: